# Generated by Django 6.0.5 on 2026-05-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(choices=[('hp', 'HP'), ('dell', 'Dell'), ('lenovo', 'Lenovo'), ('asus', 'Asus'), ('acer', 'Acer'), ('apple', 'Apple'), ('samsung', 'Samsung'), ('toshiba', 'Toshiba'), ('sony', 'Sony'), ('lg', 'LG'), ('epson', 'Epson'), ('canon', 'Canon'), ('otro', 'Otra')], max_length=20),
        ),
    ]
