# Generated by Django 6.0.5 on 2026-05-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_equipo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_estimado_texto',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
