# Generated by Django 6.0.5 on 2026-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitud_tiempo_estimado_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='confirmacion_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='observaciones_entrega',
            field=models.TextField(blank=True, default=''),
        ),
    ]
