# Generated by Django 6.0.5 on 2026-06-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ampliaciontiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tiempo_estimado_horas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
