# Generated by Django 6.0.5 on 2026-06-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_solicitud_tiempo_estimado_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(choices=[('general', 'General'), ('electronica', 'Reparación Electrónica'), ('hardware', 'Hardware'), ('software', 'Software'), ('redes', 'Redes y Conectividad'), ('otro', 'Otro')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='especialidad_otro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
