# Generated by Django 5.2.15 on 2026-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_cliente_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('recep', 'Recepcionista'), ('tec', 'Técnico'), ('admin', 'Administrador')], default='tec', max_length=10),
        ),
    ]
